<?php

return [
    'slug' => 'contact',
    'label' => 'Contactos',
    'url' => '/contact',
    'fields' => [
        'booking.title' => [
            'section' => 'Formulário de marcação',
            'label' => 'Título',
            'type' => 'textarea',
            'default' => "Faça a sua\nmarcação",
        ],
        'booking.description' => [
            'section' => 'Formulário de marcação',
            'label' => 'Descrição',
            'type' => 'textarea',
            'default' => 'Connosco operam profissionais de saúde e profissionais de estética que, aliados à tecnologia, partilham o seu conhecimento com o objetivo de lhe proporcionar os melhores resultados.',
        ],
        'form.clinics' => [
            'section' => 'Opções dos menus',
            'label' => 'Clínicas disponíveis',
            'type' => 'list',
            'add_label' => 'Adicionar clínica',
            'item_placeholder' => 'Ex: Porto',
            'default' => ['Leiria', 'Coimbra', 'Viseu', 'Vila Real', 'Porto'],
        ],
        'form.reasons' => [
            'section' => 'Opções dos menus',
            'label' => 'Motivos de marcação',
            'type' => 'list',
            'add_label' => 'Adicionar motivo',
            'item_placeholder' => 'Ex: Consulta',
            'default' => ['Tratamento laser', 'Consulta', 'Outro'],
        ],
        'form.times' => [
            'section' => 'Opções dos menus',
            'label' => 'Horários sugeridos',
            'type' => 'list',
            'add_label' => 'Adicionar horário',
            'item_placeholder' => 'Ex: 10:00',
            'default' => ['09:00', '10:00', '11:00', '14:00', '15:00', '16:00', '17:00'],
        ],
        'form.name_label' => ['editable' => false, 'default' => 'Nome'],
        'form.name_placeholder' => ['editable' => false, 'default' => 'Introduza o seu nome completo'],
        'form.email_label' => ['editable' => false, 'default' => 'Email'],
        'form.email_placeholder' => ['editable' => false, 'default' => 'exemplo@email.pt'],
        'form.phone_label' => ['editable' => false, 'default' => 'Telefone'],
        'form.phone_placeholder' => ['editable' => false, 'default' => '+351 xxx xxx xxx'],
        'form.clinic_label' => ['editable' => false, 'default' => 'Clínica'],
        'form.clinic_placeholder' => ['editable' => false, 'default' => 'Selecione a clínica'],
        'form.reason_label' => ['editable' => false, 'default' => 'Motivo de marcação'],
        'form.reason_placeholder' => ['editable' => false, 'default' => 'Selecione o motivo'],
        'form.area_label' => ['editable' => false, 'default' => 'Zona do corpo'],
        'form.area_placeholder' => ['editable' => false, 'default' => 'Axilas'],
        'form.date_label' => ['editable' => false, 'default' => 'Data preferencial'],
        'form.date_placeholder' => ['editable' => false, 'default' => 'dd/mm/yy'],
        'form.time_label' => ['editable' => false, 'default' => 'Sugestão de horário'],
        'form.time_placeholder' => ['editable' => false, 'default' => 'Hora'],
        'form.terms_text' => [
            'section' => 'Botão e termos',
            'label' => 'Texto dos termos',
            'type' => 'text',
            'default' => 'Aceito os termos e condições e a política de privacidade',
        ],
        'form.submit_text' => [
            'section' => 'Botão e termos',
            'label' => 'Texto do botão',
            'type' => 'text',
            'default' => 'Fazer Marcação',
        ],
    ],
];
